// packages/main/Framework.vue
<template>
  <section>
    <headerNav />
    p {{ loading }}22
    <div v-if="loading">loading</div>
    <div class="appContainer" v-html="content">content</div>
  </section>
</template>

<script>
import headerNav from './vue/header.vue'
export default {
  name: 'framework',
  components: { headerNav },
  props: {
    loading: Boolean,
    content: String,
  }
};
</script>

// packages/main/Framework.jsx
import React from 'react';
import Header from './react/header';
import Login from './react/login';

export default function Framework(props) {
  const { content, loading } = props;
  return (
    <>
      <Header />
      <Login />
      {loading ? <div>loading...</div> : null}
      <div dangerouslySetInnerHTML={{ __html: content }} />
    </>
  );
}
